# Column Transfer in Machine Learning ->

In [1]:
import numpy as np 
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Downloads\covid_toy.csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [4]:
df["cough"].value_counts()

cough
Mild      62
Strong    38
Name: count, dtype: int64

In [5]:
df["city"].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=["has_covid"]),df["has_covid"],test_size=0.2)

In [7]:
X_train

    age  gender  fever   cough       city
24   13  Female  100.0  Strong    Kolkata
87   47    Male  101.0  Strong  Bangalore
41   82    Male    NaN    Mild    Kolkata
14   51    Male  104.0    Mild  Bangalore
71   75  Female  104.0  Strong      Delhi
..  ...     ...    ...     ...        ...
86   25    Male  104.0    Mild  Bangalore
37   55    Male  100.0    Mild    Kolkata
96   51  Female  101.0  Strong    Kolkata
33   26  Female   98.0    Mild    Kolkata
78   11    Male  100.0    Mild  Bangalore

[80 rows x 5 columns]

1. Aam Zindagi ->

In [8]:
# adding simple imputer to fever col 

si = SimpleImputer()
X_train_fever = si.fit_transform(X_train[["fever"]])

# also the test data ->
X_test_fever = si.fit_transform(X_test[["fever"]])

X_train_fever.shape

(80, 1)

In [9]:
# ordinaLencoding -> cough 
oe = OrdinalEncoder(categories=[["Mild","Strong"]])
X_train_cough = oe.fit_transform(X_train[["cough"]])

# also the test data ->

X_test_cough = oe.fit_transform(X_test[["cough"]])

X_train_cough.shape

(80, 1)

In [10]:
# OneHotEncoding -> gender,city
ohe = OneHotEncoder(drop="first",sparse_output=False)
X_train_gender_city = ohe.fit_transform(X_train[["gender","city"]])

# also the test data ->

X_test_gender_city = ohe.fit_transform(X_test[["gender","city"]])

X_train_gender_city.shape

(80, 4)

In [11]:
# Extracting Age 
X_train_age = X_train.drop(columns=["gender","fever","cough","city"]).values

# also the test data 
X_test_age = X_test.drop(columns=["gender","fever","cough","city"]).values

X_train_age.shape

(80, 1)

# Mentos Zindagi ->

In [12]:
from sklearn.compose import ColumnTransformer

In [13]:
transformer = ColumnTransformer(transformers=[],remainder="passthrough")  # transformer name ka ak object banaya aur thn ColumnTransformer ko cll kiya aur pass karte hain transformer ka list and remainder matlab kavi kavi sab colm ke upar transformer use nehi karna hain jo basha huwa hain uske liya do option hain drop kar dea aur waisha ka waisha hi chor dena.

In [19]:
transformer = ColumnTransformer(transformers=[
    ("tnf1" , SimpleImputer(),["fever"]),
    ("tnf",OrdinalEncoder(categories=[["Mild","Strong"]]),["cough"]),
    ("tnf3",OneHotEncoder(sparse_output=False,drop="first"),["gender","city"])],remainder="passthrough")

 # yeha transformer pass karna hain tuple ke under

In [20]:
transformer.fit_transform(X_train).shape

(80, 7)

In [21]:
transformer.transform(X_test).shape

(20, 7)