# 1. Random Impute
# 2. Missing Indicator
# 3. Automatic Select of Parameter

# 1. Random Imputer -> data main jo number hain usme hi number ko randomly select karna hain aur missing places ko feel karna hain not like 1-100. Jab mean aur median use karke missing value ko fill karte hain toh distribution aur varience main difference ati hain but random impute use karte hain toh etna difference nehi ati hain.

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns   # A library used for:Data visualization 📊,Statistical plots, Better-looking graphs than Matplotlib

In [3]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Downloads\train (2).csv",usecols=["Age","Fare","Survived"])
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [4]:
df.isnull().mean()*100

Survived     0.00000
Age         19.86532
Fare         0.00000
dtype: float64

In [ ]:
X = df.drop(columns = ["Survived"])  # df = your dataset (table),So X contains all columns except Survived
y = df["Survived"]  # Selects only the Survived column,So y contains:0 → did not survive,1 → survived

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)  # Splits X and y,Creates train & test datasets,Uses 20% data for testing,Keeps result same using random_state=2

In [ ]:
X_train["Age_imputed"] = X_train["Age"]  # Takes the "Age" column from X_train,Creates a new column "Age_imputed",Copies all values into it.
X_test["Age_imputed"] = X_test["Age"]

In [8]:
X_train.head()

      Age     Fare  Age_imputed
30   40.0  27.7208         40.0
10    4.0  16.7000          4.0
873  47.0   9.0000         47.0
182   9.0  31.3875          9.0
876  20.0   9.8458         20.0

In [9]:
X_test.head()

      Age     Fare  Age_imputed
707  42.0  26.2875         42.0
37   21.0   8.0500         21.0
615  24.0  65.0000         24.0
169  28.0  56.4958         28.0
68   17.0   7.9250         17.0

In [ ]:
X_train