 agar koyi value missing hain toh iss value ko uss row ke value se fill karuge jiske  jis row main sabse similar value hain missing value ke row se.
 Euclidean distance is the straight-line distance between two points
 In KNN, we use Euclidean distance to:

 Find which points are closest
 Choose nearest neighbors

 NaN Euclidean Distance means: Calculating distance when some values are missing (NaN)
# Advantage ->                     # Disadvantages ->
 1. More accurate                  1. More no. of calculation(take lot of time)
 2.                                2. Jab vi production main diploy karte hain then toh pura traing set surver par dalna parega kioki like agar user ne kuch new point dala aur usme koyi data mising hain toh usko calculate karne ke liye X_train ka pura ka pura data use karna hota hain toh server pe memory bar jata hain

In [ ]:
import pandas as pd 
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score # Scikit-learn (sklearn) is a Python library used to:Build machine learning models,Train models,Test and evaluate models
# sklearn → Refers to the library Scikit-learn
#metrics → A module that contains functions to evaluate models
# accuracy_score → A function used to measure how correct your model predictions

In [3]:
df = pd.read_csv(r"C:\Users\Dr.Sumedha\Downloads\train (2).csv")[["Age","Pclass","Fare","Survived"]]

In [4]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [5]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [7]:
X = df.drop(columns=["Survived"])
y = df["Survived"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=2)

In [10]:
X_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [ ]:
knn = KNNImputer()

X_train_trf = knn.fit_transform(X_train)  # X_train_trf = transformed version of X_train (after filling missing values)
X_test_trf = knn.fit_transform(X_test)    #  X_test_trf is the transformed version of your test data (X_test) after handling missing values.
# fit should be done only on training data
# Test data should NOT be used for learning

In [ ]:
pd.DataFrame(X_train_trf,columns=X_train.columns)  # This line converts transformed data (X_train_trf) back into a DataFrame with proper column names.

      Age  Pclass      Fare
0    40.0     1.0   27.7208
1     4.0     3.0   16.7000
2    47.0     3.0    9.0000
3     9.0     3.0   31.3875
4    20.0     3.0    9.8458
..    ...     ...       ...
707  30.0     3.0    8.6625
708  24.2     3.0    8.7125
709  71.0     1.0   49.5042
710  28.0     1.0  221.7792
711  42.8     1.0   25.9250

[712 rows x 3 columns]

In [ ]:
lr = LogisticRegression()

lr.fit(X_train_trf, y_train)  # The model learns relationship between input and output

y_pred = lr.predict(X_test_trf) # Model gives predicted answers for test data- Output stored in y_pred

accuracy_score(y_test, y_pred) # Compare actual vs predicted and calculate accuracy

0.6983240223463687

In [17]:
# Comparision with Simple Imputer --> mean

si = SimpleImputer()

X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [18]:
lr = LogisticRegression()

lr.fit(X_train_trf2,y_train)

y_pred2 = lr.predict(X_test_trf2)

accuracy_score(y_test,y_pred2)

0.6927374301675978